/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("com.gradleup.shadow") version "9.3.0"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("com.pixelduke:transit:2.0.0")
    implementation("com.mysql:mysql-connector-j:8.3.0")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.slf4j:slf4j-simple:2.0.9")
    implementation("net.sf.jasperreports:jasperreports-jdt:7.0.3")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass.set("id.syafira.dapoer.Launcher")
    applicationDefaultJvmArgs =
        listOf("--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml", "javafx.swing")
}

tasks.shadowJar {
    archiveBaseName.set("dapoer-syafira")
    archiveVersion.set("1.0.0")
    archiveClassifier.set("")
    
    exclude("module-info.class")

    manifest {
        attributes["Main-Class"] = "id.syafira.dapoer.Launcher"
    }
}
